### ISSUE TITLE
test_runner.py fail

### ISSUE THREAD

**Issue by cryptozeny** [MicroBitcoinOrg/MicroBitcoin#14]
```bash
$ ./test/functional/test_runner.py 
Temporary test directory at /tmp/bitcoin_test_runner_20190219_155608
Traceback (most recent call last):
  File "./test/functional/test_runner.py", line 532, in <module>
    main()
  File "./test/functional/test_runner.py", line 270, in main
    run_tests(test_list, config["environment"]["SRCDIR"], config["environment"]["BUILDDIR"], config["environment"]["EXEEXT"], tmpdir, args.jobs, args.coverage, passon_args)
  File "./test/functional/test_runner.py", line 304, in run_tests
    subprocess.check_output([tests_dir + 'create_cache.py'] + flags + ["--tmpdir=%s/cache" % tmpdir])
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/ak/git/TEST-OTHER-COIN/MicroBitcoin/test/functional/create_cache.py', '--srcdir=/home/ak/git/TEST-OTHER-COIN/MicroBitcoin/src', '--configfile=/home/ak/git/TEST-OTHER-COIN/MicroBitcoin/test/functional/../config.ini', '--cachedir=/home/ak/git/TEST-OTHER-COIN/MicroBitcoin/test/cache', '--tmpdir=/tmp/bitcoin_test_runner_20190219_155608/cache']' returned non-zero exit status 1
$
```

**Comment by cryptozeny** [comment]
I'm trying to fix this. But I really do not understand... :joy:
